// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated 2020-09-03 01:01:40 +0200
package jnr.constants.platform;
public enum INet6 implements jnr.constants.Constant {
INET6_ADDRSTRLEN,
__UNKNOWN_CONSTANT__;
private static final ConstantResolver<INet6> resolver = 
ConstantResolver.getResolver(INet6.class, 20000, 29999);
public final int value() { return (int) resolver.longValue(this); }
public final int intValue() { return (int) resolver.longValue(this); }
public final long longValue() { return resolver.longValue(this); }
public final String description() { return resolver.description(this); }
public final boolean defined() { return resolver.defined(this); }
public final String toString() { return description(); }
public static INet6 valueOf(long value) { 
    return resolver.valueOf(value);
}
}
