// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated 2020-09-03 01:01:42 +0200
package jnr.constants.platform;
public enum Multicast implements jnr.constants.Constant {
MCAST_JOIN_GROUP,
MCAST_BLOCK_SOURCE,
MCAST_UNBLOCK_SOURCE,
MCAST_LEAVE_GROUP,
MCAST_JOIN_SOURCE_GROUP,
MCAST_LEAVE_SOURCE_GROUP,
MCAST_MSFILTER,
MCAST_EXCLUDE,
MCAST_INCLUDE,
__UNKNOWN_CONSTANT__;
private static final ConstantResolver<Multicast> resolver = 
ConstantResolver.getResolver(Multicast.class, 20000, 29999);
public final int value() { return (int) resolver.longValue(this); }
public final int intValue() { return (int) resolver.longValue(this); }
public final long longValue() { return resolver.longValue(this); }
public final String description() { return resolver.description(this); }
public final boolean defined() { return resolver.defined(this); }
public final String toString() { return description(); }
public static Multicast valueOf(long value) { 
    return resolver.valueOf(value);
}
}
