// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated 2018-11-29 09:39:55 +0100
package jnr.constants.platform;
public enum PollFlags implements jnr.constants.Constant {
POLLERR,
POLLHUP,
POLLIN,
POLLNVAL,
POLLOUT,
POLLPRI,
POLLRDBAND,
POLLRDNORM,
POLLWRBAND,
POLLWRNORM,
__UNKNOWN_CONSTANT__;
private static final ConstantResolver<PollFlags> resolver = 
ConstantResolver.getResolver(PollFlags.class, 20000, 29999);
public final int value() { return (int) resolver.longValue(this); }
public final byte byteValue() { return (byte) resolver.longValue(this); }
public final short shortValue() { return (short) resolver.longValue(this); }
public final int intValue() { return (int) resolver.longValue(this); }
public final long longValue() { return resolver.longValue(this); }
public final String description() { return resolver.description(this); }
public final boolean defined() { return resolver.defined(this); }
public final String toString() { return description(); }
public static PollFlags valueOf(long value) { 
    return resolver.valueOf(value);
}
}
