// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated 2018-09-09 19:50:02 +0200
package jnr.constants.platform;
public enum TCP implements jnr.constants.Constant {
TCP_MAX_SACK,
TCP_MSS,
TCP_MINMSS,
TCP_MINMSSOVERLOAD,
TCP_MAXWIN,
TCP_MAX_WINSHIFT,
TCP_MAXBURST,
TCP_MAXHLEN,
TCP_MAXOLEN,
TCP_NODELAY,
TCP_MAXSEG,
TCP_NOPUSH,
TCP_NOOPT,
TCP_KEEPALIVE,
TCP_NSTATES,
TCP_RETRANSHZ,
__UNKNOWN_CONSTANT__;
private static final ConstantResolver<TCP> resolver = 
ConstantResolver.getResolver(TCP.class, 20000, 29999);
public final int intValue() { return (int) resolver.longValue(this); }
public final long longValue() { return resolver.longValue(this); }
public final String description() { return resolver.description(this); }
public final boolean defined() { return resolver.defined(this); }
public final String toString() { return description(); }
public static TCP valueOf(long value) { 
    return resolver.valueOf(value);
}
}
