// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated Mon Feb 23 15:25:13 -0800 2009
package com.kenai.constantine.platform.freebsd;
public enum Fcntl implements com.kenai.constantine.Constant {
FREAD(1),
FWRITE(2),
FAPPEND(8),
FASYNC(64),
FFSYNC(128),
FNONBLOCK(4),
FNDELAY(4),
F_DUPFD(0),
F_GETFD(1),
F_SETFD(2),
F_GETFL(3),
F_SETFL(4),
F_GETOWN(5),
F_SETOWN(6),
F_GETLK(7),
F_SETLK(8),
F_SETLKW(9),
// F_CHKCLEAN not defined
// F_PREALLOCATE not defined
// F_SETSIZE not defined
// F_RDADVISE not defined
// F_RDAHEAD not defined
// F_READBOOTSTRAP not defined
// F_WRITEBOOTSTRAP not defined
// F_NOCACHE not defined
// F_LOG2PHYS not defined
// F_GETPATH not defined
// F_FULLFSYNC not defined
// F_PATHPKG_CHECK not defined
// F_FREEZE_FS not defined
// F_THAW_FS not defined
// F_GLOBAL_NOCACHE not defined
// F_ADDSIGS not defined
// F_MARKDEPENDENCY not defined
F_RDLCK(1),
F_UNLCK(2),
F_WRLCK(3);
// F_ALLOCATECONTIG not defined
// F_ALLOCATEALL not defined
private final int value;
private Fcntl(int value) { this.value = value; }
public static final long MIN_VALUE = 0;
public static final long MAX_VALUE = 128;

static final class StringTable {
  public static final java.util.Map<Fcntl, String> descriptions = generateTable();
  public static final java.util.Map<Fcntl, String> generateTable() {
    java.util.Map<Fcntl, String> map = new java.util.EnumMap<Fcntl, String>(Fcntl.class);
  map.put(FREAD, "Operation not permitted");
  map.put(FWRITE, "No such file or directory");
  map.put(FAPPEND, "Exec format error");
  map.put(FASYNC, "Host is down");
  map.put(FFSYNC, "Unknown error: 128");
  map.put(FNONBLOCK, "Interrupted system call");
  map.put(FNDELAY, "Interrupted system call");
  map.put(F_DUPFD, "Unknown error: 0");
  map.put(F_GETFD, "Operation not permitted");
  map.put(F_SETFD, "No such file or directory");
  map.put(F_GETFL, "No such process");
  map.put(F_SETFL, "Interrupted system call");
  map.put(F_GETOWN, "Input/output error");
  map.put(F_SETOWN, "Device not configured");
  map.put(F_GETLK, "Argument list too long");
  map.put(F_SETLK, "Exec format error");
  map.put(F_SETLKW, "Bad file descriptor");
  map.put(F_RDLCK, "Operation not permitted");
  map.put(F_UNLCK, "No such file or directory");
  map.put(F_WRLCK, "No such process");
    return map;
  }
}
public final String toString() { return StringTable.descriptions.get(this); }
public final int value() { return value; }
}
