// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated Sat Nov 29 06:34:43 +0000 2008
package com.kenai.constantine.platform.sunos;
public enum SocketLevel implements com.kenai.constantine.Constant {
SOL_SOCKET(65535);
// SOL_IP not defined
// SOL_TCP not defined
// SOL_UDP not defined
private final int value;
private SocketLevel(int value) { this.value = value; }
public static final long MIN_VALUE = 65535;
public static final long MAX_VALUE = 65535;

public final int value() { return value; }
}
