// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated Sat Nov 29 06:34:43 +0000 2008
package com.kenai.constantine.platform.sunos;
public enum Sock implements com.kenai.constantine.Constant {
SOCK_STREAM(2),
SOCK_DGRAM(1),
SOCK_RAW(4),
SOCK_RDM(5),
SOCK_SEQPACKET(6);
// SOCK_MAXADDRLEN not defined
private final int value;
private Sock(int value) { this.value = value; }
public static final long MIN_VALUE = 1;
public static final long MAX_VALUE = 6;

public final int value() { return value; }
}
