// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated Wed Feb 04 17:02:35 -0600 2009
package com.kenai.constantine.platform.fake;
public enum OpenFlags implements com.kenai.constantine.Constant {
O_RDONLY(1),
O_WRONLY(2),
O_RDWR(3),
O_ACCMODE(4),
O_NONBLOCK(5),
O_APPEND(6),
O_SYNC(7),
O_SHLOCK(8),
O_EXLOCK(9),
O_ASYNC(10),
O_FSYNC(11),
O_NOFOLLOW(12),
O_CREAT(13),
O_TRUNC(14),
O_EXCL(15),
O_EVTONLY(16),
O_DIRECTORY(17),
O_SYMLINK(18);
private final int value;
private OpenFlags(int value) { this.value = value; }
public static final long MIN_VALUE = 1;
public static final long MAX_VALUE = 18;
public final int value() { return value; }
}
