// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated Thu Nov 13 23:13:39 -0800 2008
package com.kenai.constantine.platform.fake;
public enum Shutdown implements com.kenai.constantine.Constant {
SHUT_RD(1),
SHUT_WR(2),
SHUT_RDWR(3);
private final int value;
private Shutdown(int value) { this.value = value; }
public static final long MIN_VALUE = 1;
public static final long MAX_VALUE = 3;
public final int value() { return value; }
}
