// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated Fri Jan 23 18:48:41 +1000 2009
package com.kenai.constantine.platform.fake;
public enum WaitFlags implements com.kenai.constantine.Constant {
WNOHANG(1),
WUNTRACED(2),
WSTOPPED(3),
WEXITED(4),
WCONTINUED(5),
WNOWAIT(6);
private final int value;
private WaitFlags(int value) { this.value = value; }
public static final long MIN_VALUE = 1;
public static final long MAX_VALUE = 6;
public final int value() { return value; }
}
