// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated 2018-09-09 22:13:32 +0000
package jnr.constants.platform.freebsd;
public enum AddressFamily implements jnr.constants.Constant {
AF_UNSPEC(0L),
AF_LOCAL(1L),
AF_UNIX(1L),
AF_INET(2L),
AF_IMPLINK(3L),
AF_PUP(4L),
AF_CHAOS(5L),
// AF_NS not defined
AF_ISO(7L),
AF_OSI(7L),
AF_ECMA(8L),
AF_DATAKIT(9L),
AF_CCITT(10L),
AF_SNA(11L),
AF_DECnet(12L),
AF_DLI(13L),
AF_LAT(14L),
AF_HYLINK(15L),
AF_APPLETALK(16L),
AF_ROUTE(17L),
AF_LINK(18L),
pseudo_AF_XTP(19L),
AF_COIP(20L),
AF_CNT(21L),
pseudo_AF_RTIP(22L),
AF_IPX(23L),
AF_SIP(24L),
pseudo_AF_PIP(25L),
// AF_NDRV not defined
AF_ISDN(26L),
AF_E164(26L),
pseudo_AF_KEY(27L),
AF_INET6(28L),
AF_NATM(29L),
// AF_SYSTEM not defined
AF_NETBIOS(6L),
// AF_PPP not defined
AF_ATM(30L),
pseudo_AF_HDRCMPLT(31L),
AF_NETGRAPH(32L),
// AF_AX25 not defined
AF_MAX(42L);
private final long value;
private AddressFamily(long value) { this.value = value; }
public static final long MIN_VALUE = 0L;
public static final long MAX_VALUE = 42L;

public final int intValue() { return (int) value; }
public final long longValue() { return value; }
public final boolean defined() { return true; }
}
