// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated 2020-09-19 00:15:32 +0000
package jnr.constants.platform.freebsd;
public enum AddressInfo implements jnr.constants.Constant {
AI_PASSIVE(1L),
AI_CANONNAME(2L),
AI_NUMERICHOST(4L),
AI_NUMERICSERV(8L),
AI_MASK(3343L),
AI_ALL(256L),
AI_V4MAPPED_CFG(512L),
AI_ADDRCONFIG(1024L),
AI_V4MAPPED(2048L),
AI_DEFAULT(1536L);
private final long value;
private AddressInfo(long value) { this.value = value; }
public static final long MIN_VALUE = 1L;
public static final long MAX_VALUE = 3343L;

static final class StringTable {
  public static final java.util.Map<AddressInfo, String> descriptions = generateTable();
  public static final java.util.Map<AddressInfo, String> generateTable() {
    java.util.Map<AddressInfo, String> map = new java.util.EnumMap<AddressInfo, String>(AddressInfo.class);
  map.put(AI_PASSIVE, "AI_PASSIVE");
  map.put(AI_CANONNAME, "AI_CANONNAME");
  map.put(AI_NUMERICHOST, "AI_NUMERICHOST");
  map.put(AI_NUMERICSERV, "AI_NUMERICSERV");
  map.put(AI_MASK, "AI_MASK");
  map.put(AI_ALL, "AI_ALL");
  map.put(AI_V4MAPPED_CFG, "AI_V4MAPPED_CFG");
  map.put(AI_ADDRCONFIG, "AI_ADDRCONFIG");
  map.put(AI_V4MAPPED, "AI_V4MAPPED");
  map.put(AI_DEFAULT, "AI_DEFAULT");
    return map;
  }
}
public final String toString() { return StringTable.descriptions.get(this); }
public final int value() { return (int) value; }
public final int intValue() { return (int) value; }
public final long longValue() { return value; }
public final boolean defined() { return true; }
}
