// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated 2018-09-09 22:13:34 +0000
package jnr.constants.platform.freebsd;
public enum NameInfo implements jnr.constants.Constant {
NI_MAXHOST(1025L),
NI_MAXSERV(32L),
NI_NOFQDN(1L),
NI_NUMERICHOST(2L),
NI_NAMEREQD(4L),
NI_NUMERICSERV(8L),
NI_DGRAM(16L);
// NI_WITHSCOPEID not defined
private final long value;
private NameInfo(long value) { this.value = value; }
public static final long MIN_VALUE = 1L;
public static final long MAX_VALUE = 1025L;

public final int intValue() { return (int) value; }
public final long longValue() { return value; }
public final boolean defined() { return true; }
}
