// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated 2020-09-19 00:15:35 +0000
package jnr.constants.platform.freebsd;
public enum SocketControlMessage implements jnr.constants.Constant {
SCM_RIGHTS(1L),
SCM_TIMESTAMP(2L),
// SCM_TIMESTAMPNS not defined
// SCM_TIMESTAMPING not defined
SCM_BINTIME(4L),
// SCM_CREDENTIALS not defined
SCM_CREDS(3L);
// SCM_UCRED not defined
// SCM_WIFI_STATUS not defined
private final long value;
private SocketControlMessage(long value) { this.value = value; }
public static final long MIN_VALUE = 1L;
public static final long MAX_VALUE = 4L;

static final class StringTable {
  public static final java.util.Map<SocketControlMessage, String> descriptions = generateTable();
  public static final java.util.Map<SocketControlMessage, String> generateTable() {
    java.util.Map<SocketControlMessage, String> map = new java.util.EnumMap<SocketControlMessage, String>(SocketControlMessage.class);
  map.put(SCM_RIGHTS, "SCM_RIGHTS");
  map.put(SCM_TIMESTAMP, "SCM_TIMESTAMP");
  map.put(SCM_BINTIME, "SCM_BINTIME");
  map.put(SCM_CREDS, "SCM_CREDS");
    return map;
  }
}
public final String toString() { return StringTable.descriptions.get(this); }
public final int value() { return (int) value; }
public final int intValue() { return (int) value; }
public final long longValue() { return value; }
public final boolean defined() { return true; }
}
