// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated 2020-09-19 00:15:35 +0000
package jnr.constants.platform.freebsd;
public enum TCPInfo implements jnr.constants.Constant {
TCPI_OPT_TIMESTAMPS(1L),
TCPI_OPT_SACK(2L),
TCPI_OPT_WSCALE(4L),
TCPI_OPT_ECN(8L),
// TCPI_OPT_ECN_SEEN not defined
// TCPI_OPT_SYN_DATA not defined
TCPI_OPT_TOE(16L);
private final long value;
private TCPInfo(long value) { this.value = value; }
public static final long MIN_VALUE = 1L;
public static final long MAX_VALUE = 16L;

static final class StringTable {
  public static final java.util.Map<TCPInfo, String> descriptions = generateTable();
  public static final java.util.Map<TCPInfo, String> generateTable() {
    java.util.Map<TCPInfo, String> map = new java.util.EnumMap<TCPInfo, String>(TCPInfo.class);
  map.put(TCPI_OPT_TIMESTAMPS, "TCPI_OPT_TIMESTAMPS");
  map.put(TCPI_OPT_SACK, "TCPI_OPT_SACK");
  map.put(TCPI_OPT_WSCALE, "TCPI_OPT_WSCALE");
  map.put(TCPI_OPT_ECN, "TCPI_OPT_ECN");
  map.put(TCPI_OPT_TOE, "TCPI_OPT_TOE");
    return map;
  }
}
public final String toString() { return StringTable.descriptions.get(this); }
public final int value() { return (int) value; }
public final int intValue() { return (int) value; }
public final long longValue() { return value; }
public final boolean defined() { return true; }
}
