// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated Tue Oct 14 16:06:34 +1000 2008
package constantine.platform;
public enum SocketOption implements constantine.Constant {
SO_DEBUG,
SO_ACCEPTCONN,
SO_REUSEADDR,
SO_KEEPALIVE,
SO_DONTROUTE,
SO_BROADCAST,
SO_USELOOPBACK,
SO_LINGER,
SO_OOBINLINE,
SO_REUSEPORT,
SO_TIMESTAMP,
SO_ACCEPTFILTER,
SO_DONTTRUNC,
SO_WANTMORE,
SO_WANTOOBFLAG,
SO_SNDBUF,
SO_RCVBUF,
SO_SNDLOWAT,
SO_RCVLOWAT,
SO_SNDTIMEO,
SO_RCVTIMEO,
SO_ERROR,
SO_TYPE,
SO_NREAD,
SO_NKE,
SO_NOSIGPIPE,
SO_NOADDRERR,
SO_NWRITE,
SO_REUSESHAREUID,
SO_LABEL,
SO_PEERLABEL,
__UNKNOWN_CONSTANT__;
private static final ConstantResolver<SocketOption> resolver = ConstantResolver.getResolver(SocketOption.class);
public final int value() { return resolver.intValue(this); }
public final static SocketOption valueOf(int value) { 
    return resolver.valueOf(value);
}
}
