// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated Fri Nov 14 22:41:55 +1000 2008
package com.kenai.constantine.platform.darwin;
public enum NameInfo implements com.kenai.constantine.Constant {
NI_MAXHOST(1025),
NI_MAXSERV(32),
NI_NOFQDN(1),
NI_NUMERICHOST(2),
NI_NAMEREQD(4),
NI_NUMERICSERV(8),
NI_DGRAM(16),
NI_WITHSCOPEID(32);
private final int value;
private NameInfo(int value) { this.value = value; }
public static final long MIN_VALUE = 1;
public static final long MAX_VALUE = 1025;

public final int value() { return value; }
}
