// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated Wed Feb 04 17:04:20 -0600 2009
package com.kenai.constantine.platform.darwin;
public enum OpenFlags implements com.kenai.constantine.Constant {
O_RDONLY(0),
O_WRONLY(1),
O_RDWR(2),
O_ACCMODE(3),
O_NONBLOCK(4),
O_APPEND(8),
O_SYNC(128),
O_SHLOCK(16),
O_EXLOCK(32),
O_ASYNC(64),
O_FSYNC(128),
O_NOFOLLOW(256),
O_CREAT(512),
O_TRUNC(1024),
O_EXCL(2048),
O_EVTONLY(32768),
O_DIRECTORY(1048576),
O_SYMLINK(2097152);
private final int value;
private OpenFlags(int value) { this.value = value; }
public static final long MIN_VALUE = 0;
public static final long MAX_VALUE = 2097152;

static final class StringTable {
  public static final java.util.Map<OpenFlags, String> descriptions = generateTable();
  public static final java.util.Map<OpenFlags, String> generateTable() {
    java.util.Map<OpenFlags, String> map = new java.util.EnumMap<OpenFlags, String>(OpenFlags.class);
  map.put(O_RDONLY, "Unknown error: 0");
  map.put(O_WRONLY, "Operation not permitted");
  map.put(O_RDWR, "No such file or directory");
  map.put(O_ACCMODE, "No such process");
  map.put(O_NONBLOCK, "Interrupted system call");
  map.put(O_APPEND, "Exec format error");
  map.put(O_SYNC, "Unknown error: 128");
  map.put(O_SHLOCK, "Resource busy");
  map.put(O_EXLOCK, "Broken pipe");
  map.put(O_ASYNC, "Host is down");
  map.put(O_FSYNC, "Unknown error: 128");
  map.put(O_NOFOLLOW, "Unknown error: 256");
  map.put(O_CREAT, "Unknown error: 512");
  map.put(O_TRUNC, "Unknown error: 1024");
  map.put(O_EXCL, "Unknown error: 2048");
  map.put(O_EVTONLY, "Unknown error: 32768");
  map.put(O_DIRECTORY, "Unknown error: 1048576");
  map.put(O_SYMLINK, "Unknown error: 2097152");
    return map;
  }
}
public final String toString() { return StringTable.descriptions.get(this); }
public final int value() { return value; }
}
