// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated Fri Nov 28 22:43:19 -0800 2008
package com.kenai.constantine.platform.darwin;
public enum RLIM implements com.kenai.constantine.Constant {
RLIM_NLIMITS(0x9),
RLIM_INFINITY(0xffffffff),
RLIM_SAVED_MAX(0xffffffff),
RLIM_SAVED_CUR(0xffffffff);
private final int value;
private RLIM(int value) { this.value = value; }
public static final long MIN_VALUE = 0x9;
public static final long MAX_VALUE = 0xffffffff;

public final int value() { return value; }
}
