// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated Thu Nov 13 17:05:52 +1000 2008
package com.kenai.constantine.platform.darwin;
public enum Shutdown implements com.kenai.constantine.Constant {
SHUT_RD(0),
SHUT_WR(1),
SHUT_RDWR(2);
private final int value;
private Shutdown(int value) { this.value = value; }
public static final int MIN_VALUE = 0;
public static final int MAX_VALUE = 2;

public final int value() { return value; }
}
