// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated Wed Feb 04 17:01:52 -0600 2009
package com.kenai.constantine.platform.darwin;
public enum Signal implements com.kenai.constantine.Constant {
SIGTTIN(21),
SIGTERM(15),
SIGSEGV(11),
SIGIOT(6),
SIGQUIT(3),
SIGHUP(1),
SIGIO(23),
SIGTTOU(22),
SIGTSTP(18),
SIGSTOP(17),
SIGINT(2),
SIGABRT(6),
NSIG(32),
// SIGCLD not defined
// SIGSTKFLT not defined
SIGUSR1(30),
SIGFPE(8),
SIGUSR2(31),
SIGKILL(9),
// SIGPOLL not defined
SIGXCPU(24),
SIGALRM(14),
// SIGRTMAX not defined
SIGILL(4),
// SIGUNUSED not defined
SIGURG(16),
SIGCONT(19),
SIGCHLD(20),
// SIGPWR not defined
SIGBUS(10),
SIGTRAP(5),
// SIGRTMIN not defined
SIGWINCH(28),
SIGPIPE(13),
SIGSYS(12),
SIGPROF(27),
SIGVTALRM(26),
SIGXFSZ(25);
private final int value;
private Signal(int value) { this.value = value; }
public static final long MIN_VALUE = 1;
public static final long MAX_VALUE = 32;

public final int value() { return value; }
}
