// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated Tue Nov 11 10:09:16 +1000 2008
package com.kenai.constantine.platform.linux;
public enum INAddr implements com.kenai.constantine.Constant {
INADDR_ANY(0),
INADDR_BROADCAST(-1),
INADDR_NONE(-1),
INADDR_LOOPBACK(2130706433),
INADDR_UNSPEC_GROUP(-536870912),
INADDR_ALLHOSTS_GROUP(-536870911),
INADDR_ALLRTRS_GROUP(-536870910),
INADDR_MAX_LOCAL_GROUP(-536870657);
private final int value;
private INAddr(int value) { this.value = value; }
public final int value() { return value; }
}
