// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated Mon Nov 10 18:54:09 +1000 2008
package com.kenai.constantine.platform.linux;
public enum SocketOption implements com.kenai.constantine.Constant {
SO_DEBUG(1),
SO_ACCEPTCONN(30),
SO_REUSEADDR(2),
SO_KEEPALIVE(9),
SO_DONTROUTE(5),
SO_BROADCAST(6),
// SO_USELOOPBACK not defined
SO_LINGER(13),
SO_OOBINLINE(10),
// SO_REUSEPORT not defined
SO_TIMESTAMP(29),
// SO_ACCEPTFILTER not defined
// SO_DONTTRUNC not defined
// SO_WANTMORE not defined
// SO_WANTOOBFLAG not defined
SO_SNDBUF(7),
SO_RCVBUF(8),
SO_SNDLOWAT(19),
SO_RCVLOWAT(18),
SO_SNDTIMEO(21),
SO_RCVTIMEO(20),
SO_ERROR(4),
SO_TYPE(3);
// SO_NREAD not defined
// SO_NKE not defined
// SO_NOSIGPIPE not defined
// SO_NOADDRERR not defined
// SO_NWRITE not defined
// SO_REUSESHAREUID not defined
// SO_LABEL not defined
// SO_PEERLABEL not defined
private final int value;
private SocketOption(int value) { this.value = value; }
public final int value() { return value; }
}
