// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated Fri Nov 28 12:27:59 +1000 2008
package com.kenai.constantine.platform.linux;
public enum SocketLevel implements com.kenai.constantine.Constant {
SOL_SOCKET(1);
// SOL_UDP not defined
// SOL_TCP not defined
// SOL_IP not defined
private final int value;
private SocketLevel(int value) { this.value = value; }
public static final long MIN_VALUE = 1;
public static final long MAX_VALUE = 1;

public final int value() { return value; }
}
