// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated 2017-05-18 11:46:29 -0700
package jnr.constants.platform.sparcv9.linux;
public enum RLIM implements jnr.constants.Constant {
RLIM_NLIMITS(0xfL),
RLIM_INFINITY(0xffffffffffffffffL),
RLIM_SAVED_MAX(0xffffffffffffffffL),
RLIM_SAVED_CUR(0xffffffffffffffffL);
private final long value;
private RLIM(long value) { this.value = value; }
public static final long MIN_VALUE = 0xfL;
public static final long MAX_VALUE = 0xffffffffffffffffL;

public final int intValue() { return (int) value; }
public final long longValue() { return value; }
public final boolean defined() { return true; }
}
