// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated 2017-05-18 11:46:30 -0700
package jnr.constants.platform.sparcv9.linux;
public enum RLIMIT implements jnr.constants.Constant {
RLIMIT_AS(9L),
RLIMIT_CORE(4L),
RLIMIT_CPU(0L),
RLIMIT_DATA(2L),
RLIMIT_FSIZE(1L),
RLIMIT_LOCKS(10L),
RLIMIT_MEMLOCK(8L),
RLIMIT_MSGQUEUE(12L),
RLIMIT_NICE(13L),
RLIMIT_NLIMITS(15L),
RLIMIT_NOFILE(6L),
RLIMIT_NPROC(7L),
RLIMIT_OFILE(6L),
RLIMIT_RSS(5L),
RLIMIT_RTPRIO(14L),
// RLIMIT_RTTIME not defined
RLIMIT_SIGPENDING(11L),
RLIMIT_STACK(3L);
private final long value;
private RLIMIT(long value) { this.value = value; }
public static final long MIN_VALUE = 0L;
public static final long MAX_VALUE = 15L;

public final int intValue() { return (int) value; }
public final long longValue() { return value; }
public final boolean defined() { return true; }
}
