// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated 2018-09-09 19:50:15 +0200
package jnr.constants.platform.solaris;
public enum Locale implements jnr.constants.Constant {
LC_CTYPE(0L),
LC_NUMERIC(1L),
LC_TIME(2L),
LC_COLLATE(3L),
LC_MONETARY(4L),
LC_MESSAGES(5L),
LC_ALL(6L);
// LC_PAPER not defined
// LC_NAME not defined
// LC_ADDRESS not defined
// LC_TELEPHONE not defined
// LC_MEASUREMENT not defined
// LC_IDENTIFICATION not defined
private final long value;
private Locale(long value) { this.value = value; }
public static final long MIN_VALUE = 0L;
public static final long MAX_VALUE = 6L;

public final int intValue() { return (int) value; }
public final long longValue() { return value; }
public final boolean defined() { return true; }
}
