// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated 2016-11-03 14:14:21 -0500
package jnr.constants.platform.solaris;
public enum RLIM implements jnr.constants.Constant {
RLIM_NLIMITS(0x7L),
RLIM_INFINITY(0xfffffffdL),
RLIM_SAVED_MAX(0xfffffffeL),
RLIM_SAVED_CUR(0xffffffffL);
private final long value;
private RLIM(long value) { this.value = value; }
public static final long MIN_VALUE = 0x7L;
public static final long MAX_VALUE = 0xffffffffL;

public final int intValue() { return (int) value; }
public final long longValue() { return value; }
public final boolean defined() { return true; }
}
