// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated 2016-11-03 14:14:20 -0500
package jnr.constants.platform.solaris;
public enum Sock implements jnr.constants.Constant {
SOCK_STREAM(2L),
SOCK_DGRAM(1L),
SOCK_RAW(4L),
SOCK_RDM(5L),
SOCK_SEQPACKET(6L);
// SOCK_MAXADDRLEN not defined
private final long value;
private Sock(long value) { this.value = value; }
public static final long MIN_VALUE = 1L;
public static final long MAX_VALUE = 6L;

public final int intValue() { return (int) value; }
public final long longValue() { return value; }
public final boolean defined() { return true; }
}
