// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated 2024-02-23 19:12:57 +0100
package jnr.constants.platform.fake;
public enum IPv6 implements jnr.constants.Constant {
IPV6_JOIN_GROUP(1),
IPV6_LEAVE_GROUP(2),
IPV6_MTU_DISCOVER(3),
IPV6_MULTICAST_HOPS(4),
IPV6_MULTICAST_IF(5),
IPV6_MULTICAST_LOOP(6),
IPV6_UNICAST_HOPS(7),
IPV6_V6ONLY(8),
IPV6_CHECKSUM(9),
IPV6_DONTFRAG(10),
IPV6_DSTOPTS(11),
IPV6_HOPLIMIT(12),
IPV6_HOPOPTS(13),
IPV6_NEXTHOP(14),
IPV6_PATHMTU(15),
IPV6_PKTINFO(16),
IPV6_RECVDSTOPTS(17),
IPV6_RECVERR(18),
IPV6_RECVHOPLIMIT(19),
IPV6_RECVHOPOPTS(20),
IPV6_RECVPKTINFO(21),
IPV6_RECVRTHDR(22),
IPV6_RECVTCLASS(23),
IPV6_RTHDR(24),
IPV6_RTHDRDSTOPTS(25),
IPV6_RTHDR_TYPE_0(26),
IPV6_RECVPATHMTU(27),
IPV6_TCLASS(28),
IPV6_USE_MIN_MTU(29);
private final long value;
private IPv6(long value) { this.value = value; }
public static final long MIN_VALUE = 1L;
public static final long MAX_VALUE = 29L;
public final int value() { return (int) value; }
public final int intValue() { return (int) value; }
public final long longValue() { return value; }
public final boolean defined() { return true; }
}
