// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated 2020-09-03 01:01:58 +0200
package jnr.constants.platform.fake;
public enum Local implements jnr.constants.Constant {
LOCAL_PEERCRED(1),
LOCAL_CREDS(2),
LOCAL_CONNWAIT(3);
private final long value;
private Local(long value) { this.value = value; }
public static final long MIN_VALUE = 1L;
public static final long MAX_VALUE = 3L;
public final int value() { return (int) value; }
public final int intValue() { return (int) value; }
public final long longValue() { return value; }
public final boolean defined() { return true; }
}
