// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated 2018-09-20 16:28:48 +0000
package jnr.constants.platform.fake;
public enum PosixFadvise implements jnr.constants.Constant {
POSIX_FADV_NORMAL(1),
POSIX_FADV_SEQUENTIAL(2),
POSIX_FADV_RANDOM(3),
POSIX_FADV_NOREUSE(4),
POSIX_FADV_WILLNEED(5),
POSIX_FADV_DONTNEED(6);
private final long value;
private PosixFadvise(long value) { this.value = value; }
public static final long MIN_VALUE = 1L;
public static final long MAX_VALUE = 6L;
public final int value() { return (int) value; }
public final int intValue() { return (int) value; }
public final long longValue() { return value; }
public final boolean defined() { return true; }
}
