// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated 2010-07-31 18:57:15 +1000
package jnr.constants.platform.fake;
public enum RLIM implements jnr.constants.Constant {
RLIM_NLIMITS(1),
RLIM_INFINITY(2),
RLIM_SAVED_MAX(3),
RLIM_SAVED_CUR(4);
private final long value;
private RLIM(long value) { this.value = value; }
public static final long MIN_VALUE = 1L;
public static final long MAX_VALUE = 4L;
public final int intValue() { return (int) value; }
public final long longValue() { return value; }
public final boolean defined() { return true; }
}
