// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated 2018-11-29 09:40:04 +0100
package jnr.constants.platform.fake;
public enum Shutdown implements jnr.constants.Constant {
SHUT_RD(0),
SHUT_WR(1),
SHUT_RDWR(2);
private final long value;
private Shutdown(long value) { this.value = value; }
public static final long MIN_VALUE = 0L;
public static final long MAX_VALUE = 2L;
public final int value() { return (int) value; }
public final int intValue() { return (int) value; }
public final long longValue() { return value; }
public final boolean defined() { return true; }
}
