// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated 2018-09-11 17:01:29 -0500
package jnr.constants.platform.fake;
public enum Shutdown implements jnr.constants.Constant {
SHUT_RD(1),
SHUT_WR(2),
SHUT_RDWR(3);
private final long value;
private Shutdown(long value) { this.value = value; }
public static final long MIN_VALUE = 1L;
public static final long MAX_VALUE = 3L;
public final int intValue() { return (int) value; }
public final long longValue() { return value; }
public final boolean defined() { return true; }
}
