// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated 2020-09-03 01:02:03 +0200
package jnr.constants.platform.fake;
public enum UDP implements jnr.constants.Constant {
UDP_CORK(1);
private final long value;
private UDP(long value) { this.value = value; }
public static final long MIN_VALUE = 1L;
public static final long MAX_VALUE = 1L;
public final int value() { return (int) value; }
public final int intValue() { return (int) value; }
public final long longValue() { return value; }
public final boolean defined() { return true; }
}
