// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated 2018-09-08 09:15:00 +0200
package jnr.constants.platform.linux;
public enum NameInfo implements jnr.constants.Constant {
NI_MAXHOST(1025L),
NI_MAXSERV(32L),
NI_NOFQDN(4L),
NI_NUMERICHOST(1L),
NI_NAMEREQD(8L),
NI_NUMERICSERV(2L),
NI_DGRAM(16L);
// NI_WITHSCOPEID not defined
private final long value;
private NameInfo(long value) { this.value = value; }
public static final long MIN_VALUE = 1L;
public static final long MAX_VALUE = 1025L;

public final int intValue() { return (int) value; }
public final long longValue() { return value; }
public final boolean defined() { return true; }
}
