// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated 2017-07-30 01:16:56 +0000
package jnr.constants.platform.linux;
public enum RLIMIT implements jnr.constants.Constant {
RLIMIT_AS(9L),
RLIMIT_CORE(4L),
RLIMIT_CPU(0L),
RLIMIT_DATA(2L),
RLIMIT_FSIZE(1L),
RLIMIT_LOCKS(10L),
RLIMIT_MEMLOCK(8L),
RLIMIT_MSGQUEUE(12L),
RLIMIT_NICE(13L),
RLIMIT_NLIMITS(16L),
RLIMIT_NOFILE(7L),
RLIMIT_NPROC(6L),
RLIMIT_OFILE(7L),
RLIMIT_RSS(5L),
RLIMIT_RTPRIO(14L),
RLIMIT_RTTIME(15L),
RLIMIT_SIGPENDING(11L),
RLIMIT_STACK(3L);
private final long value;
private RLIMIT(long value) { this.value = value; }
public static final long MIN_VALUE = 0L;
public static final long MAX_VALUE = 16L;

public final int intValue() { return (int) value; }
public final long longValue() { return value; }
public final boolean defined() { return true; }
}
