// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated 2018-09-12 11:05:13 +0200
package jnr.constants.platform.linux;
public enum SocketLevel implements jnr.constants.Constant {
SOL_SOCKET(1L);
// SOL_IP not defined
// SOL_TCP not defined
// SOL_UDP not defined
private final long value;
private SocketLevel(long value) { this.value = value; }
public static final long MIN_VALUE = 1L;
public static final long MAX_VALUE = 1L;

static final class StringTable {
  public static final java.util.Map<SocketLevel, String> descriptions = generateTable();
  public static final java.util.Map<SocketLevel, String> generateTable() {
    java.util.Map<SocketLevel, String> map = new java.util.EnumMap<SocketLevel, String>(SocketLevel.class);
  map.put(SOL_SOCKET, "SOL_SOCKET");
    return map;
  }
}
public final String toString() { return StringTable.descriptions.get(this); }
public final int intValue() { return (int) value; }
public final long longValue() { return value; }
public final boolean defined() { return true; }
}
