// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated 2018-11-29 09:39:58 +0100
package jnr.constants.platform.linux;
public enum TermiosFlags implements jnr.constants.Constant {
NCCS(32L),
_HAVE_STRUCT_TERMIOS_C_ISPEED(1L),
_HAVE_STRUCT_TERMIOS_C_OSPEED(1L),
VINTR(0L),
VQUIT(1L),
VERASE(2L),
VKILL(3L),
VEOF(4L),
VTIME(5L),
VMIN(6L),
VSWTC(7L),
// VSWTCH not defined
VSTART(8L),
VSTOP(9L),
VSUSP(10L),
VEOL(11L),
VREPRINT(12L),
VDISCARD(13L),
VWERASE(14L),
VLNEXT(15L),
VEOL2(16L),
IGNBRK(1L),
BRKINT(2L),
IGNPAR(4L),
PARMRK(8L),
INPCK(16L),
ISTRIP(32L),
INLCR(64L),
IGNCR(128L),
ICRNL(256L),
IUCLC(512L),
IXON(1024L),
IXANY(2048L),
IXOFF(4096L),
IMAXBEL(8192L),
IUTF8(16384L),
OPOST(1L),
OLCUC(2L),
ONLCR(4L),
OCRNL(8L),
ONOCR(16L),
ONLRET(32L),
OFILL(64L),
OFDEL(128L),
NLDLY(256L),
NL0(0L),
NL1(256L),
CRDLY(1536L),
CR0(0L),
CR1(512L),
CR2(1024L),
CR3(1536L),
TABDLY(6144L),
TAB0(0L),
TAB1(2048L),
TAB2(4096L),
TAB3(6144L),
BSDLY(8192L),
BS0(0L),
BS1(8192L),
FFDLY(32768L),
FF0(0L),
FF1(32768L),
VTDLY(16384L),
VT0(0L),
VT1(16384L),
XTABS(6144L),
CBAUD(4111L),
B0(0L),
B50(1L),
B75(2L),
B110(3L),
B134(4L),
B150(5L),
B200(6L),
B300(7L),
B600(8L),
B1200(9L),
B1800(10L),
B2400(11L),
B4800(12L),
B9600(13L),
B19200(14L),
B38400(15L),
EXTA(14L),
EXTB(15L),
CSIZE(48L),
CS5(0L),
CS6(16L),
CS7(32L),
CS8(48L),
CSTOPB(64L),
CREAD(128L),
PARENB(256L),
PARODD(512L),
HUPCL(1024L),
CLOCAL(2048L),
CBAUDEX(4096L),
B57600(4097L),
B115200(4098L),
B230400(4099L),
B460800(4100L),
B500000(4101L),
B576000(4102L),
B921600(4103L),
B1000000(4104L),
B1152000(4105L),
B1500000(4106L),
B2000000(4107L),
B2500000(4108L),
B3000000(4109L),
B3500000(4110L),
B4000000(4111L),
__MAX_BAUD(4111L),
CIBAUD(269418496L),
CMSPAR(1073741824L),
CRTSCTS(-2147483648L),
ISIG(1L),
ICANON(2L),
XCASE(4L),
ECHO(8L),
ECHOE(16L),
ECHOK(32L),
ECHONL(64L),
NOFLSH(128L),
TOSTOP(256L),
ECHOCTL(512L),
ECHOPRT(1024L),
ECHOKE(2048L),
FLUSHO(4096L),
PENDIN(16384L),
IEXTEN(32768L),
EXTPROC(65536L),
TCOOFF(0L),
TCOON(1L),
TCIOFF(2L),
TCION(3L),
TCIFLUSH(0L),
TCOFLUSH(1L),
TCIOFLUSH(2L),
TCSANOW(0L),
TCSADRAIN(1L),
TCSAFLUSH(2L);
// PAREXT not defined
private final long value;
private TermiosFlags(long value) { this.value = value; }
public static final long MIN_VALUE = -2147483648L;
public static final long MAX_VALUE = 1073741824L;

static final class StringTable {
  public static final java.util.Map<TermiosFlags, String> descriptions = generateTable();
  public static final java.util.Map<TermiosFlags, String> generateTable() {
    java.util.Map<TermiosFlags, String> map = new java.util.EnumMap<TermiosFlags, String>(TermiosFlags.class);
  map.put(NCCS, "NCCS");
  map.put(_HAVE_STRUCT_TERMIOS_C_ISPEED, "_HAVE_STRUCT_TERMIOS_C_ISPEED");
  map.put(_HAVE_STRUCT_TERMIOS_C_OSPEED, "_HAVE_STRUCT_TERMIOS_C_OSPEED");
  map.put(VINTR, "VINTR");
  map.put(VQUIT, "VQUIT");
  map.put(VERASE, "VERASE");
  map.put(VKILL, "VKILL");
  map.put(VEOF, "VEOF");
  map.put(VTIME, "VTIME");
  map.put(VMIN, "VMIN");
  map.put(VSWTC, "VSWTC");
  map.put(VSTART, "VSTART");
  map.put(VSTOP, "VSTOP");
  map.put(VSUSP, "VSUSP");
  map.put(VEOL, "VEOL");
  map.put(VREPRINT, "VREPRINT");
  map.put(VDISCARD, "VDISCARD");
  map.put(VWERASE, "VWERASE");
  map.put(VLNEXT, "VLNEXT");
  map.put(VEOL2, "VEOL2");
  map.put(IGNBRK, "IGNBRK");
  map.put(BRKINT, "BRKINT");
  map.put(IGNPAR, "IGNPAR");
  map.put(PARMRK, "PARMRK");
  map.put(INPCK, "INPCK");
  map.put(ISTRIP, "ISTRIP");
  map.put(INLCR, "INLCR");
  map.put(IGNCR, "IGNCR");
  map.put(ICRNL, "ICRNL");
  map.put(IUCLC, "IUCLC");
  map.put(IXON, "IXON");
  map.put(IXANY, "IXANY");
  map.put(IXOFF, "IXOFF");
  map.put(IMAXBEL, "IMAXBEL");
  map.put(IUTF8, "IUTF8");
  map.put(OPOST, "OPOST");
  map.put(OLCUC, "OLCUC");
  map.put(ONLCR, "ONLCR");
  map.put(OCRNL, "OCRNL");
  map.put(ONOCR, "ONOCR");
  map.put(ONLRET, "ONLRET");
  map.put(OFILL, "OFILL");
  map.put(OFDEL, "OFDEL");
  map.put(NLDLY, "NLDLY");
  map.put(NL0, "NL0");
  map.put(NL1, "NL1");
  map.put(CRDLY, "CRDLY");
  map.put(CR0, "CR0");
  map.put(CR1, "CR1");
  map.put(CR2, "CR2");
  map.put(CR3, "CR3");
  map.put(TABDLY, "TABDLY");
  map.put(TAB0, "TAB0");
  map.put(TAB1, "TAB1");
  map.put(TAB2, "TAB2");
  map.put(TAB3, "TAB3");
  map.put(BSDLY, "BSDLY");
  map.put(BS0, "BS0");
  map.put(BS1, "BS1");
  map.put(FFDLY, "FFDLY");
  map.put(FF0, "FF0");
  map.put(FF1, "FF1");
  map.put(VTDLY, "VTDLY");
  map.put(VT0, "VT0");
  map.put(VT1, "VT1");
  map.put(XTABS, "XTABS");
  map.put(CBAUD, "CBAUD");
  map.put(B0, "B0");
  map.put(B50, "B50");
  map.put(B75, "B75");
  map.put(B110, "B110");
  map.put(B134, "B134");
  map.put(B150, "B150");
  map.put(B200, "B200");
  map.put(B300, "B300");
  map.put(B600, "B600");
  map.put(B1200, "B1200");
  map.put(B1800, "B1800");
  map.put(B2400, "B2400");
  map.put(B4800, "B4800");
  map.put(B9600, "B9600");
  map.put(B19200, "B19200");
  map.put(B38400, "B38400");
  map.put(EXTA, "EXTA");
  map.put(EXTB, "EXTB");
  map.put(CSIZE, "CSIZE");
  map.put(CS5, "CS5");
  map.put(CS6, "CS6");
  map.put(CS7, "CS7");
  map.put(CS8, "CS8");
  map.put(CSTOPB, "CSTOPB");
  map.put(CREAD, "CREAD");
  map.put(PARENB, "PARENB");
  map.put(PARODD, "PARODD");
  map.put(HUPCL, "HUPCL");
  map.put(CLOCAL, "CLOCAL");
  map.put(CBAUDEX, "CBAUDEX");
  map.put(B57600, "B57600");
  map.put(B115200, "B115200");
  map.put(B230400, "B230400");
  map.put(B460800, "B460800");
  map.put(B500000, "B500000");
  map.put(B576000, "B576000");
  map.put(B921600, "B921600");
  map.put(B1000000, "B1000000");
  map.put(B1152000, "B1152000");
  map.put(B1500000, "B1500000");
  map.put(B2000000, "B2000000");
  map.put(B2500000, "B2500000");
  map.put(B3000000, "B3000000");
  map.put(B3500000, "B3500000");
  map.put(B4000000, "B4000000");
  map.put(__MAX_BAUD, "__MAX_BAUD");
  map.put(CIBAUD, "CIBAUD");
  map.put(CMSPAR, "CMSPAR");
  map.put(CRTSCTS, "CRTSCTS");
  map.put(ISIG, "ISIG");
  map.put(ICANON, "ICANON");
  map.put(XCASE, "XCASE");
  map.put(ECHO, "ECHO");
  map.put(ECHOE, "ECHOE");
  map.put(ECHOK, "ECHOK");
  map.put(ECHONL, "ECHONL");
  map.put(NOFLSH, "NOFLSH");
  map.put(TOSTOP, "TOSTOP");
  map.put(ECHOCTL, "ECHOCTL");
  map.put(ECHOPRT, "ECHOPRT");
  map.put(ECHOKE, "ECHOKE");
  map.put(FLUSHO, "FLUSHO");
  map.put(PENDIN, "PENDIN");
  map.put(IEXTEN, "IEXTEN");
  map.put(EXTPROC, "EXTPROC");
  map.put(TCOOFF, "TCOOFF");
  map.put(TCOON, "TCOON");
  map.put(TCIOFF, "TCIOFF");
  map.put(TCION, "TCION");
  map.put(TCIFLUSH, "TCIFLUSH");
  map.put(TCOFLUSH, "TCOFLUSH");
  map.put(TCIOFLUSH, "TCIOFLUSH");
  map.put(TCSANOW, "TCSANOW");
  map.put(TCSADRAIN, "TCSADRAIN");
  map.put(TCSAFLUSH, "TCSAFLUSH");
    return map;
  }
}
public final String toString() { return StringTable.descriptions.get(this); }
public final int value() { return (int) value; }
public final int intValue() { return (int) value; }
public final long longValue() { return value; }
public final boolean defined() { return true; }
}
