// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated 2019-09-24 00:13:53 +0000
package jnr.constants.platform.dragonfly5;
public enum Locale implements jnr.constants.Constant {
LC_CTYPE(2L),
LC_NUMERIC(4L),
LC_TIME(5L),
LC_COLLATE(1L),
LC_MONETARY(3L),
LC_MESSAGES(6L),
LC_ALL(0L);
// LC_PAPER not defined
// LC_NAME not defined
// LC_ADDRESS not defined
// LC_TELEPHONE not defined
// LC_MEASUREMENT not defined
// LC_IDENTIFICATION not defined
private final long value;
private Locale(long value) { this.value = value; }
public static final long MIN_VALUE = 0L;
public static final long MAX_VALUE = 6L;

static final class StringTable {
  public static final java.util.Map<Locale, String> descriptions = generateTable();
  public static final java.util.Map<Locale, String> generateTable() {
    java.util.Map<Locale, String> map = new java.util.EnumMap<Locale, String>(Locale.class);
  map.put(LC_CTYPE, "LC_CTYPE");
  map.put(LC_NUMERIC, "LC_NUMERIC");
  map.put(LC_TIME, "LC_TIME");
  map.put(LC_COLLATE, "LC_COLLATE");
  map.put(LC_MONETARY, "LC_MONETARY");
  map.put(LC_MESSAGES, "LC_MESSAGES");
  map.put(LC_ALL, "LC_ALL");
    return map;
  }
}
public final String toString() { return StringTable.descriptions.get(this); }
public final int value() { return (int) value; }
public final int intValue() { return (int) value; }
public final long longValue() { return value; }
public final boolean defined() { return true; }
}
