// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated Sat May 02 18:23:31 +1000 2009
package com.kenai.constantine.platform;
@Deprecated
public enum PRIO implements com.kenai.constantine.Constant {
PRIO_MIN,
PRIO_PROCESS,
PRIO_PGRP,
PRIO_USER,
PRIO_MAX,
__UNKNOWN_CONSTANT__;
private static final ConstantResolver<PRIO> resolver = 
ConstantResolver.getResolver(PRIO.class, 20000, 29999);
public final int value() { return resolver.intValue(this); }
public final int intValue() { return (int) resolver.longValue(this); }
public final long longValue() { return resolver.longValue(this); }
public final String description() { return resolver.description(this); }
public final boolean defined() { return true; }
public final String toString() { return description(); }
public final static PRIO valueOf(int value) { 
    return resolver.valueOf(value);
}
}
