// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated 2017-01-26 01:18:04 -0500
package jnr.constants.platform.openbsd;
public enum Locale implements jnr.constants.Constant {
LC_CTYPE(2L),
LC_NUMERIC(4L),
LC_TIME(5L),
LC_COLLATE(1L),
LC_MONETARY(3L),
LC_MESSAGES(6L),
LC_ALL(0L);
// LC_PAPER not defined
// LC_NAME not defined
// LC_ADDRESS not defined
// LC_TELEPHONE not defined
// LC_MEASUREMENT not defined
// LC_IDENTIFICATION not defined
private final long value;
private Locale(long value) { this.value = value; }
public static final long MIN_VALUE = 0L;
public static final long MAX_VALUE = 6L;

public final int intValue() { return (int) value; }
public final long longValue() { return value; }
public final boolean defined() { return true; }
}
