// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated Wed Feb 25 18:33:10 +1000 2009
package jnr.constants.platform.openbsd;
public enum NameInfo implements jnr.constants.Constant {
NI_MAXHOST(256),
NI_MAXSERV(32),
NI_NOFQDN(4),
NI_NUMERICHOST(1),
NI_NAMEREQD(8),
NI_NUMERICSERV(2),
NI_DGRAM(16);
// NI_WITHSCOPEID not defined
private final int value;
private NameInfo(int value) { this.value = value; }
public static final long MIN_VALUE = 1;
public static final long MAX_VALUE = 256;

public final int value() { return value; }
public final int intValue() { return value; }
public final long longValue() { return value; }
public final boolean defined() { return true; }
}
