// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated 2020-09-19 02:58:08 +0200
package jnr.constants.platform.openbsd;
public enum TCPInfo implements jnr.constants.Constant {
;
// TCPI_OPT_TIMESTAMPS not defined
// TCPI_OPT_SACK not defined
// TCPI_OPT_WSCALE not defined
// TCPI_OPT_ECN not defined
// TCPI_OPT_ECN_SEEN not defined
// TCPI_OPT_SYN_DATA not defined
// TCPI_OPT_TOE not defined
private final long value;
private TCPInfo(long value) { this.value = value; }
public static final long MIN_VALUE = 0L;
public static final long MAX_VALUE = 0L;

public final int value() { return (int) value; }
public final int intValue() { return (int) value; }
public final long longValue() { return value; }
public final boolean defined() { return true; }
}
