// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated 2020-09-19 02:58:09 +0200
package jnr.constants.platform.openbsd;
public enum UDP implements jnr.constants.Constant {
;
// UDP_CORK not defined
private final long value;
private UDP(long value) { this.value = value; }
public static final long MIN_VALUE = 0L;
public static final long MAX_VALUE = 0L;

public final int value() { return (int) value; }
public final int intValue() { return (int) value; }
public final long longValue() { return value; }
public final boolean defined() { return true; }
}
