// WARNING: This file is autogenerated. DO NOT EDIT!
// Generated Tue Oct 14 15:42:08 +1000 2008
package constantine.platform.darwin;
public enum Shutdown implements constantine.Constant {
SHUT_RD(0),
SHUT_WR(1),
SHUT_RDWR(2);
private final int value;
private Shutdown(int value) { this.value = value; }
public final int value() { return value; }
}
